version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
  celery_amqp:
    build: ./celery_amqp 
    command: python "./task_publisher.py"
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
      - redis
  celery_worker:
    build: ./celery_worker
    command: celery worker -A tasks --loglevel=INFO
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
      - redis